/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as NotesRpcRouteImport } from './routes/notes/rpc'
import { Route as NotesNewRouteImport } from './routes/notes/new'
import { Route as NotesGqlRouteImport } from './routes/notes/gql'
import { Route as NotesClientRouteImport } from './routes/notes/client'
import { Route as ApiRegisterRouteImport } from './routes/api/register'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiGraphqlRouteImport } from './routes/api/graphql'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as NotesIdIndexRouteImport } from './routes/notes/$id/index'
import { Route as ApiNotesIndexRouteImport } from './routes/api/notes/index'
import { Route as NotesIdEditRouteImport } from './routes/notes/$id/edit'
import { Route as ApiPushUnsubscribeRouteImport } from './routes/api/push/unsubscribe'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as ApiNotesIdRouteImport } from './routes/api/notes/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRpcRoute = NotesRpcRouteImport.update({
  id: '/notes/rpc',
  path: '/notes/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNewRoute = NotesNewRouteImport.update({
  id: '/notes/new',
  path: '/notes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesGqlRoute = NotesGqlRouteImport.update({
  id: '/notes/gql',
  path: '/notes/gql',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesClientRoute = NotesClientRouteImport.update({
  id: '/notes/client',
  path: '/notes/client',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterRoute = ApiRegisterRouteImport.update({
  id: '/api/register',
  path: '/api/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphqlRoute = ApiGraphqlRouteImport.update({
  id: '/api/graphql',
  path: '/api/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdIndexRoute = NotesIdIndexRouteImport.update({
  id: '/notes/$id/',
  path: '/notes/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesIndexRoute = ApiNotesIndexRouteImport.update({
  id: '/api/notes/',
  path: '/api/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdEditRoute = NotesIdEditRouteImport.update({
  id: '/notes/$id/edit',
  path: '/notes/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushUnsubscribeRoute = ApiPushUnsubscribeRouteImport.update({
  id: '/api/push/unsubscribe',
  path: '/api/push/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesIdRoute = ApiNotesIdRouteImport.update({
  id: '/api/notes/$id',
  path: '/api/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/events': typeof ApiEventsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/me': typeof ApiMeRoute
  '/api/register': typeof ApiRegisterRoute
  '/notes/client': typeof NotesClientRoute
  '/notes/gql': typeof NotesGqlRoute
  '/notes/new': typeof NotesNewRoute
  '/notes/rpc': typeof NotesRpcRoute
  '/notes/': typeof NotesIndexRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/notes/$id/edit': typeof NotesIdEditRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/notes/$id/': typeof NotesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/events': typeof ApiEventsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/me': typeof ApiMeRoute
  '/api/register': typeof ApiRegisterRoute
  '/notes/client': typeof NotesClientRoute
  '/notes/gql': typeof NotesGqlRoute
  '/notes/new': typeof NotesNewRoute
  '/notes/rpc': typeof NotesRpcRoute
  '/notes': typeof NotesIndexRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/notes/$id/edit': typeof NotesIdEditRoute
  '/api/notes': typeof ApiNotesIndexRoute
  '/notes/$id': typeof NotesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/events': typeof ApiEventsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/me': typeof ApiMeRoute
  '/api/register': typeof ApiRegisterRoute
  '/notes/client': typeof NotesClientRoute
  '/notes/gql': typeof NotesGqlRoute
  '/notes/new': typeof NotesNewRoute
  '/notes/rpc': typeof NotesRpcRoute
  '/notes/': typeof NotesIndexRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/notes/$id/edit': typeof NotesIdEditRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/notes/$id/': typeof NotesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/api/events'
    | '/api/graphql'
    | '/api/login'
    | '/api/logout'
    | '/api/me'
    | '/api/register'
    | '/notes/client'
    | '/notes/gql'
    | '/notes/new'
    | '/notes/rpc'
    | '/notes/'
    | '/api/notes/$id'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
    | '/notes/$id/edit'
    | '/api/notes/'
    | '/notes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/api/events'
    | '/api/graphql'
    | '/api/login'
    | '/api/logout'
    | '/api/me'
    | '/api/register'
    | '/notes/client'
    | '/notes/gql'
    | '/notes/new'
    | '/notes/rpc'
    | '/notes'
    | '/api/notes/$id'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
    | '/notes/$id/edit'
    | '/api/notes'
    | '/notes/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/api/events'
    | '/api/graphql'
    | '/api/login'
    | '/api/logout'
    | '/api/me'
    | '/api/register'
    | '/notes/client'
    | '/notes/gql'
    | '/notes/new'
    | '/notes/rpc'
    | '/notes/'
    | '/api/notes/$id'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
    | '/notes/$id/edit'
    | '/api/notes/'
    | '/notes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiGraphqlRoute: typeof ApiGraphqlRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiRegisterRoute: typeof ApiRegisterRoute
  NotesClientRoute: typeof NotesClientRoute
  NotesGqlRoute: typeof NotesGqlRoute
  NotesNewRoute: typeof NotesNewRoute
  NotesRpcRoute: typeof NotesRpcRoute
  NotesIndexRoute: typeof NotesIndexRoute
  ApiNotesIdRoute: typeof ApiNotesIdRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiPushUnsubscribeRoute: typeof ApiPushUnsubscribeRoute
  NotesIdEditRoute: typeof NotesIdEditRoute
  ApiNotesIndexRoute: typeof ApiNotesIndexRoute
  NotesIdIndexRoute: typeof NotesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/rpc': {
      id: '/notes/rpc'
      path: '/notes/rpc'
      fullPath: '/notes/rpc'
      preLoaderRoute: typeof NotesRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/new': {
      id: '/notes/new'
      path: '/notes/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof NotesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/gql': {
      id: '/notes/gql'
      path: '/notes/gql'
      fullPath: '/notes/gql'
      preLoaderRoute: typeof NotesGqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/client': {
      id: '/notes/client'
      path: '/notes/client'
      fullPath: '/notes/client'
      preLoaderRoute: typeof NotesClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register': {
      id: '/api/register'
      path: '/api/register'
      fullPath: '/api/register'
      preLoaderRoute: typeof ApiRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql': {
      id: '/api/graphql'
      path: '/api/graphql'
      fullPath: '/api/graphql'
      preLoaderRoute: typeof ApiGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id/': {
      id: '/notes/$id/'
      path: '/notes/$id'
      fullPath: '/notes/$id/'
      preLoaderRoute: typeof NotesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/': {
      id: '/api/notes/'
      path: '/api/notes'
      fullPath: '/api/notes/'
      preLoaderRoute: typeof ApiNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id/edit': {
      id: '/notes/$id/edit'
      path: '/notes/$id/edit'
      fullPath: '/notes/$id/edit'
      preLoaderRoute: typeof NotesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/unsubscribe': {
      id: '/api/push/unsubscribe'
      path: '/api/push/unsubscribe'
      fullPath: '/api/push/unsubscribe'
      preLoaderRoute: typeof ApiPushUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/$id': {
      id: '/api/notes/$id'
      path: '/api/notes/$id'
      fullPath: '/api/notes/$id'
      preLoaderRoute: typeof ApiNotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiGraphqlRoute: ApiGraphqlRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiMeRoute: ApiMeRoute,
  ApiRegisterRoute: ApiRegisterRoute,
  NotesClientRoute: NotesClientRoute,
  NotesGqlRoute: NotesGqlRoute,
  NotesNewRoute: NotesNewRoute,
  NotesRpcRoute: NotesRpcRoute,
  NotesIndexRoute: NotesIndexRoute,
  ApiNotesIdRoute: ApiNotesIdRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiPushUnsubscribeRoute: ApiPushUnsubscribeRoute,
  NotesIdEditRoute: NotesIdEditRoute,
  ApiNotesIndexRoute: ApiNotesIndexRoute,
  NotesIdIndexRoute: NotesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
