import { Jimp } from "jimp";
import { mkdirSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { createMaskable, createMonochrome } from "./maskable.js";

const LEGACY_DENSITIES: Record<string, number> = {
  mdpi: 48,
  hdpi: 72,
  xhdpi: 96,
  xxhdpi: 144,
  xxxhdpi: 192,
};

const FOREGROUND_RESOLUTION = 216; // 108dp @ xxxhdpi (2x)

const ADAPTIVE_SAFE_ZONE = 0.66;

export interface AndroidOptions {
  basePng: Buffer;
  /** Packed RGBA background color (see hexToRgbaInt in generate.ts) */
  backgroundColor: number;
  /** Packed RGBA theme color used for the monochrome layer */
  themeColor: number;
  /** Solid hex color string for values/colors.xml */
  backgroundColorHex: string;
  outputDir: string;
  appName: string;
  files: string[];
  onProgress?: (message: string) => void;
}

async function createAdaptiveForeground(sourcePng: Buffer, size: number): Promise<Buffer> {
  const image = await Jimp.read(sourcePng);
  const canvas = new Jimp({ width: size, height: size, color: 0x00000000 });
  const fit = Math.round(size * ADAPTIVE_SAFE_ZONE);
  const scale = fit / Math.max(image.bitmap.width, image.bitmap.height);
  const newW = Math.round(image.bitmap.width * scale);
  const newH = Math.round(image.bitmap.height * scale);
  image.resize({ w: newW, h: newH });
  canvas.composite(image, Math.round((size - newW) / 2), Math.round((size - newH) / 2));
  return canvas.getBuffer("image/png");
}

function writePng(filePath: string, buffer: Buffer): void {
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, buffer);
}

function writeAdaptiveXml(filePath: string, monochrome: boolean): void {
  const mono = monochrome
    ? `\n    <monochrome android:drawable="@mipmap/ic_launcher_monochrome" />`
    : "";
  const xml = `<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />${mono}
</adaptive-icon>
`;
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, xml);
}

/**
 * Generates the standard Android launcher stack: density-scaled legacy
 * `ic_launcher` / `ic_launcher_round` PNGs, the `mipmap-anydpi-v26` adaptive
 * icon XMLs (background / foreground / monochrome layers), and the color
 * resource they reference.
 */
export async function generateAndroidAdaptiveIcons(opts: AndroidOptions): Promise<void> {
  const { basePng, backgroundColor, backgroundColorHex, themeColor, outputDir, appName, files, onProgress } = opts;

  for (const [density, size] of Object.entries(LEGACY_DENSITIES)) {
    onProgress?.(`Android ${density} launcher...`);
    const launcher = await createMaskable(basePng, size, backgroundColor);
    files.push(join(outputDir, `mipmap-${density}`, "ic_launcher.png"));
    files.push(join(outputDir, `mipmap-${density}`, "ic_launcher_round.png"));
    writePng(files[files.length - 2], launcher);
    writePng(files[files.length - 1], launcher);
  }

  onProgress?.("Android adaptive foreground...");
  const foreground = await createAdaptiveForeground(basePng, FOREGROUND_RESOLUTION);
  const monochrome = await createMonochrome(basePng, FOREGROUND_RESOLUTION, themeColor);
  const fgPath = join(outputDir, "mipmap-xxxhdpi", "ic_launcher_foreground.png");
  const monoPath = join(outputDir, "mipmap-xxxhdpi", "ic_launcher_monochrome.png");
  writePng(fgPath, foreground);
  writePng(monoPath, monochrome);
  files.push(fgPath, monoPath);

  const launcherXml = join(outputDir, "mipmap-anydpi-v26", "ic_launcher.xml");
  const roundXml = join(outputDir, "mipmap-anydpi-v26", "ic_launcher_round.xml");
  writeAdaptiveXml(launcherXml, true);
  writeAdaptiveXml(roundXml, true);
  files.push(launcherXml, roundXml);

  const colorsPath = join(outputDir, "values", "colors.xml");
  mkdirSync(dirname(colorsPath), { recursive: true });
  writeFileSync(
    colorsPath,
    `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">${backgroundColorHex}</color>
</resources>
`,
  );
  files.push(colorsPath);

  const notePath = join(outputDir, "android-adaptive-icons.txt");
  writeFileSync(
    notePath,
    `Android adaptive icons generated by @swoff/assets (${appName})

1. Copy the mipmap-*/ and values/ directories into your Android project's
   res/ directory (merging with existing folders).

2. The mipmap-anydpi-v26/ adaptive icon XMLs satisfy Android 8+ (API 26+)
   devices. The density-scaled mipmap ic_launcher/ic_launcher_round PNGs
   cover legacy devices and launchers.

3. If your app is served as a PWA, keep manifest.json's maskable icons —
   those cover the home-screen install path; the mipmaps here are for
   native/WebView wrappers (e.g. Trusted Web Activity).
`,
  );
  files.push(notePath);
}